### ISSUE TITLE
Just letting you know...

### ISSUE THREAD

**Issue by wiledal** [dokipen/batbelt#1]
We use `Keystone` and can't run `npm shrinkwrap` because of `batbelt` being dependant on `hashish` with an unspecified version 😢 

```
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: have hashish@0.0.4 (expected: ) <REDACTED>/node_modules/batbelt/node_modules/hashish
npm ERR! extraneous: hashish@0.0.4 <REDACTED>/node_modules/batbelt/node_modules/hashish
```

**Comment by dokipen** [comment]
Wow, didn't know anyone used batbelt, lol. I'll fix.

**Comment by dokipen** [comment]
Fixed, but people should really use lodash instead of this. I created it a long time ago before I knew about lodash.
